describe('slides', function()
  -- Require module at the top level
  local slides = require('presenterm.slides')

  describe('module structure', function()
    it('should export required functions', function()
      assert.is_function(slides.get_frontmatter_end)
      assert.is_function(slides.get_slide_positions)
      assert.is_function(slides.get_current_slide)
      assert.is_function(slides.is_presentation)
      assert.is_function(slides.new_slide)
      assert.is_function(slides.split_slide)
      assert.is_function(slides.delete_slide)
      assert.is_function(slides.yank_slide)
      assert.is_function(slides.select_slide)
      assert.is_function(slides.get_slide_content)
      assert.is_function(slides.move_slide_up)
      assert.is_function(slides.move_slide_down)
      assert.is_function(slides.interactive_reorder)
    end)
  end)
end)
