name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim_version: ['nightly', 'stable']

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}